site_name: Instacord
site_description: A Python-based discord bot made for downloading and creating Instagram posts.
repo_url: https://github.com/mattsolstice/Instacord

theme:
  name: material
  font:
    code: Fira Code
  pallete:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - search.highlight
    - search.suggest

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/]
  - git-authors
  - glightbox
  - offline
  - search:
      lang: en

markdown_extensions:
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

nav:
  - Home:
    - Overview: index.md
    - License: license.md